### ISSUE TITLE
Emails are bouncing

### ISSUE THREAD

**Issue by kwinkunks** [offentlig-paas/nye.offentlig-paas.no#72]
FYI when I wrote to ask about an invite to the Slack, I got this:

> Delivery has failed to these recipients or groups:
> 
> kontakt <at> offentlig-paas.no
> 
> Your message wasn't delivered. Despite repeated attempts to deliver your message, the recipient's email system refused to accept a connection from your email system.

**Comment by Starefossen** [comment]
Ooops, thanks for the heads up! Fixing the email now!
